### ISSUE TITLE
Verifying the installation Failed with OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by RoManInv** [utopia-group/Smore#1]
Hello Utopia Group,
I have encountered OverflowError: Python int too large to convert to C long after installing all the dependencies of Smore project. This happens to the both python3-command you have provided for verifying the installation. It would be really nice if you could help me with this issue. 

* Full stack trace:
```
(smore) PS D:\Project\Smore> python -W ignore test_dsl.py 
Traceback (most recent call last):
  File "D:\Project\Smore\test_dsl.py", line 6, in <module>
    from lib.interpreter.executor import Executor
  File "D:\Project\Smore\lib\interpreter\executor.py", line 10, in <module>
    from lib.interpreter.context import StrContext, EntityPreprocessContext
  File "D:\Project\Smore\lib\interpreter\context.py", line 9, in <module>
    from lib.nlp.nlp import NLPFunc, date_template_match3
  File "D:\Project\Smore\lib\nlp\nlp.py", line 25, in <module>
    from lib.utils.matcher_utils import double_check_ent, find_date, sub_date_time_detect
  File "D:\Project\Smore\lib\utils\matcher_utils.py", line 17, in <module>
    from lib.utils.csv_utils import read_csv_to_dict
  File "D:\Project\Smore\lib\utils\csv_utils.py", line 11, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
```

```
(smore) PS D:\Project\Smore> python -W ignore test_overall_synthesizer.py 
Traceback (most recent call last):
  File "D:\Project\Smore\test_overall_synthesizer.py", line 2, in <module>
    from lib.synthesizer.top_level_synthesizer import TopLevelSynthesizer
  File "D:\Project\Smore\lib\synthesizer\top_level_synthesizer.py", line 6, in <module>
    from lib.eval.eval_res import EvalRes
  File "D:\Project\Smore\lib\eval\eval_res.py", line 3, in <module>
    from lib.interpreter.pattern import Pattern
  File "D:\Project\Smore\lib\interpreter\pattern.py", line 8, in <module>
    from lib.interpreter.context import StrContext
  File "D:\Project\Smore\lib\interpreter\context.py", line 9, in <module>
    from lib.nlp.nlp import NLPFunc, date_template_match3
  File "D:\Project\Smore\lib\nlp\nlp.py", line 25, in <module>
    from lib.utils.matcher_utils import double_check_ent, find_date, sub_date_time_detect
  File "D:\Project\Smore\lib\utils\matcher_utils.py", line 17, in <module>
    from lib.utils.csv_utils import read_csv_to_dict
  File "D:\Project\Smore\lib\utils\csv_utils.py", line 11, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
```

* System spec:
  - OS: Windows 11 64 Bit
  - Spec: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz with 64GB RAM

* Installation of dependencies:
  - curl: not installed. Rust installed from `https://rustup.rs/`
  - gcc: Successfully installed from official windows-installer, PATH variable added and test passed
  - clang: Successfully compiled and built following official instructions, PATH variable added and test passed
  - python3-dev: not installed, as installing python=3.10 on windows automatically installs %python_path%/includes that does the same thing as python3-dev on Mac or Linux
  - dotnet 5.0: Successfully installed

* Installing python packages:
  - pip install -r requirements.txt: failed when installing fasttext, using fasttext-wheel 0.9.2 instead. Other packages are installed successfully
  - spaCy: Successfully installed

* Exporting OpenAI-API: pending, as I currently don't plan to run new tasks, but only reproduce the results from your paper.

Additionally, the reason that I compile from your source code is that I cannot build the docker image due to the following error:

```
 => ERROR [10/17] RUN pip install -r requirements.txt                                                              0.7s
------
 > [10/17] RUN pip install -r requirements.txt:
0.577 error: externally-managed-environment
0.577
0.577 × This environment is externally managed
0.577 ╰─> To install Python packages system-wide, try apt install
0.577     python3-xyz, where xyz is the package you are trying to
0.577     install.
0.577
0.577     If you wish to install a non-Debian-packaged Python package,
0.577     create a virtual environment using python3 -m venv path/to/venv.
0.577     Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
0.577     sure you have python3-full installed.
0.577
0.577     If you wish to install a non-Debian packaged Python application,
0.577     it may be easiest to use pipx install xyz, which will manage a
0.577     virtual environment for you. Make sure you have pipx installed.
0.577
0.577     See /usr/share/doc/python3.12/README.venv for more information.
0.577
0.577 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
0.577 hint: See PEP 668 for the detailed specification.
------
Dockerfile:45
--------------------
  43 |     COPY requirements.txt /Smore
  44 |
  45 | >>> RUN pip install -r requirements.txt
  46 |
  47 |     RUN python3 -m spacy download en_core_web_md
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
```

The reason I mix these both issues together is that I assume either problem solved will make Smore running on my PC. 

It would be really nice if you could help me with this issue, thank you very much.

**Comment by RoManInv** [comment]
The problem is (temporarily) solved. The solution is to change the parent image into ubuntu:jammy (standing for Ubuntu 22.04 LTS) and change the `python3-dev` in apt-get into `python3.10-dev`

I have tried to fix the Dockerfile to build an image for the project. The parent image ubuntu:latest (standing for Ubuntu 24.04 LTS) is breaking the installation, as the package `python3-dev` on that is based on Python 3.12, while the project requires Python 3.10. Such mismatch causes the installation of SpaCy to break on installation and compilation. Note that `python3.10-dev` is not supported in Ubuntu 24.04 (with ppa `notable` instead of `jammy`), so that `apt-get install python3.10-dev` will fail.

I have created a PR for this fix and hope it could help fixing the docker image.

The installation from source code on Windows remains unsolved. Other inspections are needed to fix the overflow issue (maybe endian of the package is the problem?) I'm happy to provide additional info if you try to fix that problem.
